Restructure the project for new versioning approach
py-mine/mcproto pull request #116
Opened 2023-06-08 16:48 UTC by ItsDrike

This PR resolves #45, and restructures the entire project to no longer support multiple minecraft protocol versions, moving to a single (latest) version model.

Note that **this is a completely breaking change, and there will NOT be a deprecation period**. This is because of how this change impacts the rest of the project development. As this project is still in pre-release stage, deprecation here would greatly slow down any further development here, forcing contributors to maintain both the temporary deprecation layer, and the new single-version one.

For more details on how this change will affect the project going forward, and why it is necessary, I'd suggest checking out #45, containing a detailed explanation.

I have updated the README examples which now use this updated version, so I'd suggest checking that out before moving forward with trying out this version, as it will almost certainly break any existing code-bases using mcproto.

2023-06-09 19:46 UTC, ItsDrike commented on mcproto/packets/packet_map.py
> +def _walk_submodules(module: ModuleType) -> Iterator[WalkableModuleData]:
I don't think this is a huge issue, it's an internal function, and the docstring describes what's being done here, I also don't really see a good way to make this function much simpler.

2023-06-09 19:49 UTC, ItsDrike commented on mcproto/packets/packet_map.py
> +def generate_packet_map(direction: PacketDirection, state: GameState) -> Mapping[int, type[Packet]]:
This function actually really isn't particularly complex or hard to understand.

2023-06-11 17:51 UTC, Martysh12 requested changes
That looks good to me, but that last point bugs me a little.
- I like the idea of importing packets dynamically, as maintaining a big dictionary of packets does seem like a pain.
- I don't mind the memory overhead caching gives the library, because importing is a slow procedure.
- Is it possible to return some kind of "immutable dictionary", so that you don't have to copy the dictionary? Maybe `MappingProxyType` from the `types` module? (available since Python 3.3)

2023-06-11 17:56 UTC, ItsDrike commented
> Is it possible to return some kind of "immutable dictionary", so that you don't have to copy the dictionary? Maybe MappingProxyType from the types module? (available since Python 3.3)

This is a nice idea, however you need the real dictionary to be kept somewhere, and since a function call creates a new stackframe, with all of the variables in it, and as the function ends, that stackframe gets deleted, along with all the variables it held. You could probably do something hacky, like crating a global variable, holding a list of dictionaries, which are the return values, so that the caching then returns that mapping proxy back, with the actual dict being in that global variable list. But this is probably way too convoluted and I'm not sure I love that.

I do also find this caching with copying pretty annoying though, I just wasn't able to think of anything better. Btw, do you think the name `utils/decorators.py` works well here? Or can you think of a better name? I didn't want an overly specific name just for this copying logic, to avoid too many files in utils dir, but decorators might be a bit too broad. Not sure where else to put it / what to call that file.

2023-06-11 18:06 UTC, ItsDrike commented
Hmm, actually after some testing, it seems like this would work, as `MappingProxyType` does count as an object holding a direct reference to the original `dict`, so it's more like returning a class holding a dict inside of it. I assumed mapping proxy worked more like a weakref. In this case I would agree that just returning a mapping proxy would probably work pretty well.

2023-06-11 18:10 UTC, Martysh12 approved these changes
> This is a nice idea, however you need the real dictionary to be kept somewhere, and since a function call creates a new stackframe, with all of the variables in it, as the function ends, that stackframe gets deleted, and that means taking all of the local variables it held alongside. A mapping proxy needs a reference to an actual dict object, so we can't have that dict going out of scope, while the mapping proxy is returned.
> You could probably do something hacky, like crating a global variable, holding a list of dictionaries, which are the return values, so that the caching then returns that mapping proxy back, with the actual dict being in that global variable list. But this is probably way too convoluted and I'm not sure I love that.

Riiight. Oh well, copying is not that bad after all.

> Btw, do you think the name `utils/decorators.py` works well here? Or can you think of a better name? I didn't want an overly specific name just for this copying logic, to avoid too many files in utils dir, but decorators might be a bit too broad. Not sure where else to put it / what to call that file.

I can't think of a better name than `utils/decorators.py`, so I guess it's final.

I'll approve the changes, then.

2023-06-11 18:30 UTC, merged