Increase test coverage
py-mine/mcproto pull request #35
Opened 2023-02-16 19:14 UTC by Martysh12

## Why
Increasing test coverage to _at least_ 75% is a milestone this project has to reach before 1.0.0.

## What
This pull request adds more tests, and tweaks coverage parameters in order to achieve this milestone.

Closes #10

2023-02-20 23:35 UTC, Martysh12 commented
I've reached the goal! Coverage is 77.37%.

2023-02-21 20:58 UTC, ItsDrike requested changes

2023-02-21 20:58 UTC, ItsDrike commented on tests/mcproto/packets/v757/status/test_status.py
> +    # but Python adds spaces after commas and colons.
Can't we just use the `json` library to parse that out into a pure dict for verification?

2023-02-23 12:57 UTC, ItsDrike commented on tests/mcproto/packets/v757/status/test_status.py
> +    expected_buffer.read_varint()  # Clear the JSON length data.
Great! Just mention why we're clearing the JSON length here and it's good to go

2023-02-23 20:10 UTC, ItsDrike approved these changes

2023-02-23 20:10 UTC, merged